# fly.toml app configuration file generated for entangled-club on 2025-10-15T18:12:28-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'entangled-club'
primary_region = 'ord'

[build]

[env]
  # Rails config
  LOCAL_DOMAIN = "entangled.club"
  WEB_DOMAIN = "entangled.club"
  RAILS_BIND = "0.0.0.0"
  SERVER_HOST = "0.0.0.0"
  DB_POOL = "25"
  MAX_THREADS = "5"
  RAILS_LOG_LEVEL = "info"
  SIDEKIQ_LOG_LEVEL = "info"
  SIDEKIQ_CONCURRENCY = "10"
  WEB_CONCURRENCY = "2"
  # SMTP via Resend
  SMTP_DELIVERY_METHOD = "smtp"
  SMTP_FROM_ADDRESS = "noreply@email.entangled.club"
  SMTP_LOGIN = "resend"
  SMTP_PORT = "587"
  SMTP_SERVER = "smtp.resend.com"
  # Object storage via Tigris
  EXTRA_MEDIA_HOSTS = "aged-wind-2023.fly.storage.tigris.dev"
  S3_BUCKET = "aged-wind-2023"
  S3_ENABLED = "true"
  S3_ENDPOINT = "https://fly.storage.tigris.dev"
  S3_HOSTNAME = "fly.storage.tigris.dev"
  S3_OVERRIDE_PATH_STYLE = "false"
  S3_REGION = "auto"
  # Security settings
  AUTHORIZED_FETCH = "true"
  DISALLOW_UNAUTHENTICATED_API_ACCESS = "true"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
